name: Python Build
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        required: false
        default: dev

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: python-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}


jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev'}}

    outputs:
      image_tag: ${{ steps.vars.outputs.IMAGE_TAG }}
      short_sha: ${{ steps.vars.outputs.SHORT_SHA }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Generate variable
        id: vars
        shell: bash
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=sha-$SHORT_SHA" >> $GITHUB_OUTPUT
      
      - name: Print variables
        run: |
          echo "$PYTHON_VERSION"
          echo "$IMAGE_NAME"
          echo "$AWS_REGION"
  
  ruff:
    runs-on: ubuntu-latest
    environment: dev
    needs: prepare

    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          #cache-dependeny-path: requirements.txt
      
      - name: install dependeny
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff  

      - name: Run Ruff
        run: |
          ruff check .  
      
      - name: Ruff format check
        continue-on-error: true
        run: |
          ruff format --check .

  pytest:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    needs: prepare
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependeny
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov

      - name: Run unit test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest \
          --cov=src \
          --cov-report=xml \
          --cov-report=term

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml             
  
  snyk:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    needs: prepare
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependeny
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install snyk
        run: npm install -g snyk

      - name: Authenticate snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Dependeny scan
        run: snyk test -- json > dependeny-report.json
        continue-on-error: true

      # - name: Source code scan
      #   run: snyk code test
      #   continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: synk-dependeny-scan
          path: dependeny-report.json












  # python-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4
  #     - name: setup python package
  #       run: |
  #         pip install -r requirements.txt
  #         echo "Packages Installed" >> $GITHUB_STEP_SUMMARY
  #     - name: setup ruff
  #       run: |
  #         ruff check .
  #         echo "Ruff check passed" >> $GITHUB_STEP_SUMMARY
  #     - name: setup pytest
  #       run: |
  #         python -m pytest
  #         echo "pytest passed" >> $GITHUB_STEP_SUMMARY
  #     - name: docker build
  #       run: |
  #         docker build -t python:v1 .

