name: Python build

on:
  push:
    branches:
     - main
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: false
        default: dev
        type: string

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: python-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Quality-Check:
    uses: ./.github/workflows/quality.yml
    with:
      env: ${{ inputs.env || 'dev' }}
    secrets: inherit
  
  Python-Build:
    uses: ./.github/workflows/python-build.yml
    needs: Quality-Check
    with:
      env: ${{ inputs.env || 'dev' }}
      image-tag: ${{ needs.Quality-Check.outputs.image_tag }}
    secrets: inherit